DROP DATABASE IF EXISTS empresa;
CREATE DATABASE empresa;
USE empresa;

CREATE TABLE FUNCIONARIO(
pnome VARCHAR(15) NOT NULL,
minicial CHAR,
unome VARCHAR(15) NOT NULL,
cpf CHAR(9) NOT NULL,
data_nasc DATE,
endereco VARCHAR(30),
sexo CHAR,
salario NUMERIC(10,2),
cpf_supervisor CHAR(9),
Dnr INT NOT NULL DEFAULT 1,
PRIMARY KEY (cpf)
);

CREATE TABLE DEPARTAMENTO(
dnome VARCHAR(20) NOT NULL,
dnumero INT NOT NULL,
cpf_gerente CHAR(9) NOT NULL DEFAULT '888665555',
ger_data_ini DATE,
PRIMARY KEY (dnumero),
UNIQUE (dnome), -- Departamentos não podem ter o mesmo nome
FOREIGN KEY (cpf_gerente) REFERENCES FUNCIONARIO(cpf)
ON UPDATE CASCADE
);


CREATE TABLE LOCALIZACOES_DEP
(
dnumero INT NOT NULL,
dlocalizacao VARCHAR(15) NOT NULL,
PRIMARY KEY (dnumero, dlocalizacao),
FOREIGN KEY (dnumero) REFERENCES DEPARTAMENTO(dnumero)
ON DELETE CASCADE
ON UPDATE CASCADE );

CREATE TABLE PROJETO
( 
pnome VARCHAR(20) NOT NULL,
pnumero INT NOT NULL,
plocalizacao VARCHAR(15),
dnum INT NOT NULL,
PRIMARY KEY (pnumero),
UNIQUE (pnome),
FOREIGN KEY (dnum) REFERENCES DEPARTAMENTO(dnumero) );

CREATE TABLE TRABALHA_EM
( fcpf CHAR(9) NOT NULL,
pnr INT NOT NULL,
Horas DECIMAL(3,1),
PRIMARY KEY (fcpf, pnr),
FOREIGN KEY (fcpf) REFERENCES FUNCIONARIO(cpf) 
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (pnr) REFERENCES PROJETO(pnumero)
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE DEPENDENTE
( 
fcpf CHAR(9) NOT NULL,
nome_dependente VARCHAR(15) NOT NULL,
sexo CHAR,
data_nasc DATE,
parentesco VARCHAR(8),
PRIMARY KEY (fcpf, Nome_dependente),
FOREIGN KEY (fcpf) REFERENCES FUNCIONARIO(cpf)
ON DELETE CASCADE
ON UPDATE CASCADE );